import AuthForms from "@/components/screens/AuthForms";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Autenticação | Ciganos Encantados",
  description: "Generated by create next app",
};

const Auth = () => {
  return (
    <div className="flex flex-col h-full mt-10 mb-10 items-center justify-center space-y-5">
      <Link href={"/"}>
        <p className="text-xl">
          <span className="text-first">Ciganos</span> Encantados
        </p>
      </Link>
      <AuthForms />
    </div>
  );
};

export default Auth;
