import LoginForm from "@/components/forms/LoginForm";
import AuthForms from "@/components/screens/AuthForms";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Autenticação | Cartas Misticas",
  description: "Generated by create next app",
};

const Auth = () => {
  return (
    <div className="flex flex-col h-full mt-10 mb-10 items-center justify-center space-y-5">
      <Link href={"/"}>
        <p className="text-xl">
          <span className="text-first">Cartas</span> Misticas
        </p>
      </Link>
      <AuthForms />
    </div>
  );
};

export default Auth;
