import { Chat } from "@/components/chat/chat";
import { ChatLayout } from "@/components/chat/chat-layout";
import { MobileView } from "@/components/chat/mobileScreen";
import { Sidebar } from "@/components/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Conversas | Cartas Misticas",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="flex ">
      <MobileView />
    </main>
  );
};

export default page;
