import { MobileView } from "@/components/chat/mobileScreen";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Conversas | Ciganos Encantados",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="flex ">
      <MobileView />
    </main>
  );
};

export default page;
