import { ChatLayout } from "@/components/chat/chat-layout";
import { Sidebar } from "@/components/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Conversas | Ciganos Encantados",
  description: "Generated by create next app",
};

const page = ({ params }: { params: { id: string } }) => {
  return (
    <main className="flex ">
      <Sidebar />
      <ChatLayout
        id={params.id}
        defaultLayout={undefined}
        navCollapsedSize={8}
      />
    </main>
  );
};

export default page;
