import Footer from "@/components/footer";
import HomeHeader from "@/components/header/HomeHeader";
import Pricing from "@/components/Pricing";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Créditos   | Cartas Misticas",
  description: "Generated by create next app",
};

function page() {
  return (
    <main>
      <HomeHeader />
      <Pricing />
      <Footer />
    </main>
  );
}

export default page;
