import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./reduxProvider";
import RecoilContextProvider from "./recoilContextProvider";
import { Toaster } from "@/components/ui/toaster";
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ciganos Encantados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <RecoilContextProvider>
          <body className={poppins.className}>
            <main>
              {children}
              <Toaster />
            </main>
          </body>
        </RecoilContextProvider>
      </ReduxProvider>
    </html>
  );
}
