import { Admin } from "@/components/admin";
import Footer from "@/components/footer";
import HomeHeader from "@/components/header/HomeHeader";
import Pricing from "@/components/Pricing";
import { HomeSidebar } from "@/components/sidebar/homeSideBar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Admin | Ciganos Encantados",
  description: "Generated by create next app",
};


function Page() {
  return (
    <main>
      <HomeHeader />
      <Admin />
      <Footer />
    </main>
  );
}

export default Page;
